-- Contenu des pages légales (mentions légales, confidentialité), stocké en
-- HTML dans la table site_settings existante pour être éditable depuis
-- /admin/settings sans avoir à toucher au code à chaque changement.
-- Préremplit avec le contenu initial (avec les [À COMPLÉTER] à remplir).
INSERT INTO site_settings (key, value) VALUES (
  'mentions_legales_content',
  '<section><h2>Éditeur du site</h2><p>Nom / raison sociale : <strong>[À COMPLÉTER — ex: Association Pas de planète B]</strong><br>Forme juridique : <strong>[À COMPLÉTER — ex: association loi 1901]</strong><br>Adresse du siège : <strong>[À COMPLÉTER]</strong><br>SIRET (si applicable) : <strong>[À COMPLÉTER]</strong><br>Directeur·rice de la publication : <strong>[À COMPLÉTER]</strong><br>Email de contact : <strong>[À COMPLÉTER]</strong></p></section><section><h2>Hébergement</h2><p>Le site est hébergé par <strong>Digital Forest</strong>, marque de la société <strong>GreenWeb SAS</strong>, société par actions simplifiée au capital variable.<br>Siège social : 5 rue de l''Industrie, 74000 Annecy, France<br>RCS Annecy B 882 060 056<br>Téléphone : 03 62 02 50 35<br>Site web : <a href="https://digitalforest.fr" target="_blank" rel="noreferrer">digitalforest.fr</a></p></section><section><h2>Propriété intellectuelle et licence</h2><p>Le code source de ce site est distribué sous licence libre <strong>GNU Affero General Public License v3.0 (AGPL-3.0)</strong>. Le dépôt de code, incluant le texte complet de la licence, est consultable publiquement sur GitHub.</p><p>Les contenus éditoriaux (textes de la charte éthique, débunks, présentation des rubriques) sont la propriété de l''éditeur du site, sauf mention contraire. Les données chiffrées présentées proviennent de sources publiques officielles, citées sur chaque page concernée.</p></section><section><h2>Responsabilité</h2><p>Les informations diffusées sur ce site le sont à titre informatif. Malgré le soin apporté à leur exactitude et à leur mise à jour régulière, l''éditeur ne saurait garantir l''exhaustivité ou l''absence d''erreur des données présentées, notamment lorsqu''elles proviennent de jeux de données publics tiers.</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'confidentialite_content',
  '<p>Cette page décrit quelles données personnelles sont collectées sur ce site, pourquoi, et comment vous pouvez exercer vos droits, conformément au RGPD.</p><section><h2>Responsable du traitement</h2><p><strong>[À COMPLÉTER — nom de l''association/éditeur]</strong>, dont les coordonnées figurent sur la page Mentions légales, est responsable du traitement des données décrites ci-dessous.</p></section><section><h2>Ce que nous collectons</h2><p>Ce site n''a pas de système de compte utilisateur. Les données collectées sont : un identifiant anonyme pour les votes citoyens (droit à l''oubli intégré depuis la page Mes votes), une adresse email en cas d''inscription volontaire à la newsletter ou au suivi d''un député, et le texte des suggestions soumises volontairement.</p></section><section><h2>Cookies et traceurs</h2><p>Ce site n''utilise pas de cookies publicitaires ni de traceurs tiers. Les préférences d''affichage sont stockées localement dans votre navigateur et ne quittent jamais votre appareil.</p></section><section><h2>Hébergement des données</h2><p>Les données sont hébergées en France, chez Digital Forest (GreenWeb SAS, Annecy).</p></section><section><h2>Vos droits</h2><p>Conformément au RGPD, vous disposez d''un droit d''accès, de rectification, d''effacement, de limitation et d''opposition. Pour toute demande, contactez <strong>[À COMPLÉTER — email de contact]</strong>. Vous pouvez aussi contacter la CNIL.</p></section>'
) ON CONFLICT (key) DO NOTHING;
