-- Contenu des pages légales par langue. Les clés sans suffixe restent le
-- français (comportement historique, inchangé) ; _en/_es/_it sont les
-- nouvelles variantes ajoutées avec le multilingue phase 2.
INSERT INTO site_settings (key, value) VALUES (
  'mentions_legales_content_en',
  '<section><h2>Site publisher</h2><p>Name / legal form: <strong>[TO BE COMPLETED — e.g. Association Pas de planète B]</strong><br>Legal status: <strong>[TO BE COMPLETED]</strong><br>Registered address: <strong>[TO BE COMPLETED]</strong><br>Registration number (if applicable): <strong>[TO BE COMPLETED]</strong><br>Publication director: <strong>[TO BE COMPLETED]</strong><br>Contact email: <strong>[TO BE COMPLETED]</strong></p></section><section><h2>Hosting</h2><p>This site is hosted by <strong>Digital Forest</strong>, a brand of <strong>GreenWeb SAS</strong>.<br>Registered office: 5 rue de l''Industrie, 74000 Annecy, France<br>RCS Annecy B 882 060 056<br>Phone: +33 3 62 02 50 35<br>Website: <a href="https://digitalforest.fr" target="_blank" rel="noreferrer">digitalforest.fr</a></p></section><section><h2>Intellectual property and licence</h2><p>The source code of this site is distributed under the free <strong>GNU Affero General Public License v3.0 (AGPL-3.0)</strong>. The code repository, including the full licence text, is publicly available on GitHub.</p><p>Editorial content is the property of the site publisher, unless stated otherwise. Data figures presented come from official public sources, cited on each relevant page.</p></section><section><h2>Liability</h2><p>Information published on this site is for informational purposes. Despite our care for accuracy and regular updates, the publisher cannot guarantee the completeness or absence of errors in the data presented, particularly when sourced from third-party public datasets.</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'mentions_legales_content_es',
  '<section><h2>Editor del sitio</h2><p>Nombre / forma jurídica: <strong>[POR COMPLETAR — ej: Asociación Pas de planète B]</strong><br>Forma jurídica: <strong>[POR COMPLETAR]</strong><br>Domicilio social: <strong>[POR COMPLETAR]</strong><br>Número de registro (si aplica): <strong>[POR COMPLETAR]</strong><br>Director de publicación: <strong>[POR COMPLETAR]</strong><br>Email de contacto: <strong>[POR COMPLETAR]</strong></p></section><section><h2>Alojamiento</h2><p>El sitio está alojado por <strong>Digital Forest</strong>, marca de <strong>GreenWeb SAS</strong>.<br>Domicilio social: 5 rue de l''Industrie, 74000 Annecy, Francia<br>RCS Annecy B 882 060 056<br>Teléfono: +33 3 62 02 50 35<br>Sitio web: <a href="https://digitalforest.fr" target="_blank" rel="noreferrer">digitalforest.fr</a></p></section><section><h2>Propiedad intelectual y licencia</h2><p>El código fuente de este sitio se distribuye bajo la licencia libre <strong>GNU Affero General Public License v3.0 (AGPL-3.0)</strong>. El repositorio del código, incluyendo el texto completo de la licencia, está disponible públicamente en GitHub.</p><p>Los contenidos editoriales son propiedad del editor del sitio, salvo mención contraria. Las cifras de datos presentadas provienen de fuentes públicas oficiales, citadas en cada página correspondiente.</p></section><section><h2>Responsabilidad</h2><p>La información publicada en este sitio tiene fines informativos. A pesar del cuidado dedicado a su exactitud y actualización regular, el editor no puede garantizar la exhaustividad o ausencia de errores en los datos presentados, especialmente cuando provienen de fuentes públicas de terceros.</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'mentions_legales_content_it',
  '<section><h2>Editore del sito</h2><p>Nome / forma giuridica: <strong>[DA COMPLETARE — es: Associazione Pas de planète B]</strong><br>Forma giuridica: <strong>[DA COMPLETARE]</strong><br>Sede legale: <strong>[DA COMPLETARE]</strong><br>Numero di registrazione (se applicabile): <strong>[DA COMPLETARE]</strong><br>Direttore della pubblicazione: <strong>[DA COMPLETARE]</strong><br>Email di contatto: <strong>[DA COMPLETARE]</strong></p></section><section><h2>Hosting</h2><p>Il sito è ospitato da <strong>Digital Forest</strong>, marchio di <strong>GreenWeb SAS</strong>.<br>Sede legale: 5 rue de l''Industrie, 74000 Annecy, Francia<br>RCS Annecy B 882 060 056<br>Telefono: +33 3 62 02 50 35<br>Sito web: <a href="https://digitalforest.fr" target="_blank" rel="noreferrer">digitalforest.fr</a></p></section><section><h2>Proprietà intellettuale e licenza</h2><p>Il codice sorgente di questo sito è distribuito sotto licenza libera <strong>GNU Affero General Public License v3.0 (AGPL-3.0)</strong>. Il repository del codice, incluso il testo completo della licenza, è pubblicamente consultabile su GitHub.</p><p>I contenuti editoriali sono di proprietà dell''editore del sito, salvo diversa indicazione. I dati numerici presentati provengono da fonti pubbliche ufficiali, citate in ogni pagina interessata.</p></section><section><h2>Responsabilità</h2><p>Le informazioni pubblicate su questo sito hanno scopo informativo. Nonostante la cura dedicata alla loro accuratezza e all''aggiornamento regolare, l''editore non può garantire la completezza o l''assenza di errori nei dati presentati, in particolare quando provengono da set di dati pubblici di terzi.</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'confidentialite_content_en',
  '<p>This page describes what personal data is collected on this site, why, and how you can exercise your rights, in accordance with the GDPR.</p><section><h2>Data controller</h2><p><strong>[TO BE COMPLETED — publisher name]</strong>, whose details appear on the Legal Notice page, is responsible for the data processing described below.</p></section><section><h2>What we collect</h2><p>This site has no user account system. Data collected: an anonymous identifier for citizen votes (right to erasure available from the My Votes page), an email address for voluntary newsletter or deputy-follow sign-ups, and the text of voluntarily submitted suggestions.</p></section><section><h2>Cookies and trackers</h2><p>This site does not use advertising cookies or third-party trackers. Display preferences are stored locally in your browser and never leave your device.</p></section><section><h2>Data hosting</h2><p>Data is hosted in France, at Digital Forest (GreenWeb SAS, Annecy).</p></section><section><h2>Your rights</h2><p>Under the GDPR, you have the right to access, rectify, erase, restrict and object to your personal data. For any request, contact <strong>[TO BE COMPLETED — contact email]</strong>. You may also contact your national data protection authority.</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'confidentialite_content_es',
  '<p>Esta página describe qué datos personales se recopilan en este sitio, por qué, y cómo puedes ejercer tus derechos, conforme al RGPD.</p><section><h2>Responsable del tratamiento</h2><p><strong>[POR COMPLETAR — nombre del editor]</strong>, cuyos datos figuran en la página de Mentions légales, es responsable del tratamiento de los datos descritos a continuación.</p></section><section><h2>Qué recopilamos</h2><p>Este sitio no tiene sistema de cuentas de usuario. Los datos recopilados son: un identificador anónimo para los votos ciudadanos (derecho al olvido disponible desde la página Mis votos), una dirección de correo en caso de inscripción voluntaria al boletín o al seguimiento de un diputado, y el texto de las sugerencias enviadas voluntariamente.</p></section><section><h2>Cookies y rastreadores</h2><p>Este sitio no utiliza cookies publicitarias ni rastreadores de terceros. Las preferencias de visualización se almacenan localmente en tu navegador y nunca salen de tu dispositivo.</p></section><section><h2>Alojamiento de los datos</h2><p>Los datos están alojados en Francia, en Digital Forest (GreenWeb SAS, Annecy).</p></section><section><h2>Tus derechos</h2><p>Conforme al RGPD, dispones de un derecho de acceso, rectificación, supresión, limitación y oposición. Para cualquier solicitud, contacta con <strong>[POR COMPLETAR — email de contacto]</strong>. También puedes contactar con tu autoridad de protección de datos.</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'confidentialite_content_it',
  '<p>Questa pagina descrive quali dati personali vengono raccolti su questo sito, perché, e come puoi esercitare i tuoi diritti, in conformità al GDPR.</p><section><h2>Titolare del trattamento</h2><p><strong>[DA COMPLETARE — nome dell''editore]</strong>, i cui dati figurano nella pagina Note legali, è responsabile del trattamento dei dati descritti di seguito.</p></section><section><h2>Cosa raccogliamo</h2><p>Questo sito non ha un sistema di account utente. I dati raccolti sono: un identificatore anonimo per i voti dei cittadini (diritto all''oblio disponibile dalla pagina I miei voti), un indirizzo email in caso di iscrizione volontaria alla newsletter o al monitoraggio di un deputato, e il testo dei suggerimenti inviati volontariamente.</p></section><section><h2>Cookie e tracciatori</h2><p>Questo sito non utilizza cookie pubblicitari né tracciatori di terze parti. Le preferenze di visualizzazione sono memorizzate localmente nel tuo browser e non lasciano mai il tuo dispositivo.</p></section><section><h2>Hosting dei dati</h2><p>I dati sono ospitati in Francia, presso Digital Forest (GreenWeb SAS, Annecy).</p></section><section><h2>I tuoi diritti</h2><p>In conformità al GDPR, hai diritto di accesso, rettifica, cancellazione, limitazione e opposizione. Per qualsiasi richiesta, contatta <strong>[DA COMPLETARE — email di contatto]</strong>. Puoi anche contattare la tua autorità di protezione dei dati.</p></section>'
) ON CONFLICT (key) DO NOTHING;
