-- Contenu des pages légales en russe, japonais, chinois et hindi.
-- Comme pour les autres langues, à relire par un locuteur natif avant
-- publication — en particulier ici, où la terminologie juridique est plus
-- sensible aux nuances culturelles/légales locales.

INSERT INTO site_settings (key, value) VALUES (
  'mentions_legales_content_ru',
  '<section><h2>Издатель сайта</h2><p>Название / организационно-правовая форма: <strong>[ЗАПОЛНИТЬ]</strong><br>Юридическая форма: <strong>[ЗАПОЛНИТЬ]</strong><br>Юридический адрес: <strong>[ЗАПОЛНИТЬ]</strong><br>Регистрационный номер (если применимо): <strong>[ЗАПОЛНИТЬ]</strong><br>Директор публикации: <strong>[ЗАПОЛНИТЬ]</strong><br>Электронная почта для связи: <strong>[ЗАПОЛНИТЬ]</strong></p></section><section><h2>Хостинг</h2><p>Сайт размещён компанией <strong>Digital Forest</strong>, торговой маркой <strong>GreenWeb SAS</strong>.<br>Юридический адрес: 5 rue de l''Industrie, 74000 Annecy, Франция<br>RCS Annecy B 882 060 056<br>Телефон: +33 3 62 02 50 35<br>Сайт: <a href="https://digitalforest.fr" target="_blank" rel="noreferrer">digitalforest.fr</a></p></section><section><h2>Интеллектуальная собственность и лицензия</h2><p>Исходный код этого сайта распространяется по свободной лицензии <strong>GNU Affero General Public License v3.0 (AGPL-3.0)</strong>. Репозиторий кода, включая полный текст лицензии, публично доступен на GitHub.</p><p>Редакционные материалы являются собственностью издателя сайта, если не указано иное. Приведённые данные получены из официальных открытых источников, указанных на каждой странице.</p></section><section><h2>Ответственность</h2><p>Информация, публикуемая на этом сайте, носит информационный характер. Несмотря на внимание к точности и регулярному обновлению, издатель не может гарантировать полноту или отсутствие ошибок в представленных данных, особенно если они получены из сторонних открытых источников.</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'mentions_legales_content_ja',
  '<section><h2>サイト発行者</h2><p>名称 / 法的形態: <strong>[要記入]</strong><br>法的形態: <strong>[要記入]</strong><br>所在地: <strong>[要記入]</strong><br>登録番号（該当する場合）: <strong>[要記入]</strong><br>発行責任者: <strong>[要記入]</strong><br>連絡先メール: <strong>[要記入]</strong></p></section><section><h2>ホスティング</h2><p>このサイトは <strong>GreenWeb SAS</strong> のブランドである <strong>Digital Forest</strong> によりホストされています。<br>所在地: 5 rue de l''Industrie, 74000 Annecy, フランス<br>RCS Annecy B 882 060 056<br>電話: +33 3 62 02 50 35<br>ウェブサイト: <a href="https://digitalforest.fr" target="_blank" rel="noreferrer">digitalforest.fr</a></p></section><section><h2>知的財産権とライセンス</h2><p>このサイトのソースコードは、自由ライセンスである <strong>GNU Affero General Public License v3.0 (AGPL-3.0)</strong> の下で配布されています。ライセンス全文を含むコードリポジトリはGitHubで公開されています。</p><p>編集コンテンツは、特に断りのない限りサイト発行者の所有物です。掲載されているデータは、各ページに記載されている公式な公開情報源に基づいています。</p></section><section><h2>責任</h2><p>このサイトに掲載されている情報は情報提供のみを目的としています。正確性と定期的な更新には注意を払っていますが、発行者は、特に第三者の公開データセットに由来する場合、掲載データの完全性や誤りがないことを保証することはできません。</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'mentions_legales_content_zh',
  '<section><h2>网站发布者</h2><p>名称 / 法律形式：<strong>[待填写]</strong><br>法律形式：<strong>[待填写]</strong><br>注册地址：<strong>[待填写]</strong><br>注册号码（如适用）：<strong>[待填写]</strong><br>出版负责人：<strong>[待填写]</strong><br>联系邮箱：<strong>[待填写]</strong></p></section><section><h2>托管服务</h2><p>本网站由 <strong>GreenWeb SAS</strong> 旗下品牌 <strong>Digital Forest</strong> 托管。<br>注册地址：5 rue de l''Industrie, 74000 Annecy, 法国<br>RCS Annecy B 882 060 056<br>电话：+33 3 62 02 50 35<br>网站：<a href="https://digitalforest.fr" target="_blank" rel="noreferrer">digitalforest.fr</a></p></section><section><h2>知识产权与许可证</h2><p>本网站的源代码根据自由许可证 <strong>GNU Affero General Public License v3.0 (AGPL-3.0)</strong> 分发。代码仓库（含许可证全文）可在GitHub上公开查阅。</p><p>除另有说明外，编辑内容归网站发布者所有。所展示的数据来自各相关页面所引用的官方公开来源。</p></section><section><h2>责任声明</h2><p>本网站发布的信息仅供参考。尽管我们努力确保数据准确并定期更新，发布者无法保证所呈现数据的完整性或不含错误，尤其是当数据来自第三方公开数据集时。</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'mentions_legales_content_hi',
  '<section><h2>साइट प्रकाशक</h2><p>नाम / कानूनी रूप: <strong>[भरना है]</strong><br>कानूनी रूप: <strong>[भरना है]</strong><br>पंजीकृत पता: <strong>[भरना है]</strong><br>पंजीकरण संख्या (यदि लागू हो): <strong>[भरना है]</strong><br>प्रकाशन निदेशक: <strong>[भरना है]</strong><br>संपर्क ईमेल: <strong>[भरना है]</strong></p></section><section><h2>होस्टिंग</h2><p>यह साइट <strong>GreenWeb SAS</strong> के ब्रांड <strong>Digital Forest</strong> द्वारा होस्ट की जाती है।<br>पंजीकृत कार्यालय: 5 rue de l''Industrie, 74000 Annecy, फ्रांस<br>RCS Annecy B 882 060 056<br>फोन: +33 3 62 02 50 35<br>वेबसाइट: <a href="https://digitalforest.fr" target="_blank" rel="noreferrer">digitalforest.fr</a></p></section><section><h2>बौद्धिक संपदा और लाइसेंस</h2><p>इस साइट का स्रोत कोड मुक्त लाइसेंस <strong>GNU Affero General Public License v3.0 (AGPL-3.0)</strong> के तहत वितरित किया गया है। लाइसेंस के पूर्ण पाठ सहित कोड रिपॉजिटरी GitHub पर सार्वजनिक रूप से उपलब्ध है।</p><p>संपादकीय सामग्री साइट प्रकाशक की संपत्ति है, जब तक अन्यथा न बताया जाए। प्रस्तुत डेटा आधिकारिक सार्वजनिक स्रोतों से आता है, जिनका उल्लेख प्रत्येक संबंधित पृष्ठ पर किया गया है।</p></section><section><h2>दायित्व</h2><p>इस साइट पर प्रकाशित जानकारी सूचनात्मक उद्देश्यों के लिए है। सटीकता और नियमित अद्यतन के प्रति सावधानी के बावजूद, प्रकाशक प्रस्तुत डेटा की पूर्णता या त्रुटि-मुक्तता की गारंटी नहीं दे सकता, विशेष रूप से जब यह तृतीय-पक्ष सार्वजनिक डेटासेट से प्राप्त हो।</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'confidentialite_content_ru',
  '<p>Эта страница описывает, какие персональные данные собираются на этом сайте, зачем, и как вы можете реализовать свои права в соответствии с GDPR.</p><section><h2>Оператор данных</h2><p><strong>[ЗАПОЛНИТЬ — название издателя]</strong>, реквизиты которого указаны на странице «Юридическая информация», отвечает за обработку описанных ниже данных.</p></section><section><h2>Что мы собираем</h2><p>На этом сайте нет системы учётных записей пользователей. Собираемые данные: анонимный идентификатор для гражданских голосований (право на удаление доступно на странице «Мои голоса»), адрес электронной почты при добровольной подписке на рассылку или отслеживание депутата, и текст добровольно отправленных предложений.</p></section><section><h2>Файлы cookie и трекеры</h2><p>Этот сайт не использует рекламные файлы cookie или сторонние трекеры. Настройки отображения сохраняются локально в вашем браузере и никогда не покидают ваше устройство.</p></section><section><h2>Хостинг данных</h2><p>Данные размещены во Франции, у Digital Forest (GreenWeb SAS, Annecy).</p></section><section><h2>Ваши права</h2><p>В соответствии с GDPR у вас есть право на доступ, исправление, удаление, ограничение и возражение в отношении ваших данных. По любым запросам обращайтесь по адресу <strong>[ЗАПОЛНИТЬ — контактный email]</strong>. Вы также можете обратиться в орган по защите данных вашей страны.</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'confidentialite_content_ja',
  '<p>このページでは、このサイトでどのような個人データが収集されるか、その理由、そしてGDPRに従ってどのように権利を行使できるかについて説明します。</p><section><h2>データ管理者</h2><p>「法的表示」ページに記載されている <strong>[要記入 — 発行者名]</strong> が、以下に説明するデータ処理の責任者です。</p></section><section><h2>収集する情報</h2><p>このサイトにはユーザーアカウントシステムはありません。収集されるデータ：市民投票のための匿名識別子（「自分の投票」ページから削除可能）、ニュースレターまたは議員フォローへの任意登録時のメールアドレス、および任意に送信された提案のテキストです。</p></section><section><h2>Cookieとトラッカー</h2><p>このサイトは広告Cookieや第三者トラッカーを使用しません。表示設定はブラウザにローカルに保存され、お使いのデバイスから外に出ることはありません。</p></section><section><h2>データのホスティング</h2><p>データはフランスのDigital Forest（GreenWeb SAS、Annecy）でホストされています。</p></section><section><h2>あなたの権利</h2><p>GDPRに基づき、あなたはご自身のデータへのアクセス、訂正、削除、制限、異議申し立ての権利を有します。ご質問は <strong>[要記入 — 連絡先メール]</strong> までご連絡ください。データ保護機関にも連絡することができます。</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'confidentialite_content_zh',
  '<p>本页说明本网站收集哪些个人数据、原因为何，以及您如何依据GDPR行使自己的权利。</p><section><h2>数据控制者</h2><p><strong>[待填写 — 发布者名称]</strong>（其详细信息见「法律声明」页面）负责处理以下所述数据。</p></section><section><h2>我们收集的信息</h2><p>本网站没有用户账户系统。收集的数据包括：用于公民投票的匿名标识符（可从「我的投票」页面行使被遗忘权）、自愿订阅通讯或关注议员时提供的电子邮箱地址，以及自愿提交的建议文本。</p></section><section><h2>Cookie与追踪器</h2><p>本网站不使用广告Cookie或第三方追踪器。显示偏好设置本地存储在您的浏览器中，绝不会离开您的设备。</p></section><section><h2>数据托管</h2><p>数据托管于法国的Digital Forest（GreenWeb SAS，安纳西）。</p></section><section><h2>您的权利</h2><p>根据GDPR，您享有对自己数据的访问权、更正权、删除权、限制权和反对权。如有任何请求，请联系 <strong>[待填写 — 联系邮箱]</strong>。您也可以联系您所在地区的数据保护主管机构。</p></section>'
) ON CONFLICT (key) DO NOTHING;

INSERT INTO site_settings (key, value) VALUES (
  'confidentialite_content_hi',
  '<p>यह पृष्ठ बताता है कि इस साइट पर कौन सा व्यक्तिगत डेटा एकत्र किया जाता है, क्यों, और आप GDPR के अनुसार अपने अधिकारों का प्रयोग कैसे कर सकते हैं।</p><section><h2>डेटा नियंत्रक</h2><p><strong>[भरना है — प्रकाशक का नाम]</strong>, जिनका विवरण «कानूनी सूचना» पृष्ठ पर दिया गया है, नीचे वर्णित डेटा प्रसंस्करण के लिए जिम्मेदार है।</p></section><section><h2>हम क्या एकत्र करते हैं</h2><p>इस साइट में कोई उपयोगकर्ता खाता प्रणाली नहीं है। एकत्र किया गया डेटा: नागरिक वोटों के लिए एक गुमनाम पहचानकर्ता («मेरे वोट» पृष्ठ से मिटाने का अधिकार उपलब्ध), न्यूज़लेटर या सांसद अनुसरण के लिए स्वैच्छिक पंजीकरण के मामले में एक ईमेल पता, और स्वेच्छा से प्रस्तुत सुझावों का पाठ।</p></section><section><h2>कुकीज़ और ट्रैकर</h2><p>यह साइट विज्ञापन कुकीज़ या तृतीय-पक्ष ट्रैकर का उपयोग नहीं करती। प्रदर्शन प्राथमिकताएं आपके ब्राउज़र में स्थानीय रूप से संग्रहीत होती हैं और कभी भी आपके डिवाइस से बाहर नहीं जातीं।</p></section><section><h2>डेटा होस्टिंग</h2><p>डेटा फ्रांस में, Digital Forest (GreenWeb SAS, Annecy) पर होस्ट किया जाता है।</p></section><section><h2>आपके अधिकार</h2><p>GDPR के अनुसार, आपके पास अपने डेटा तक पहुंच, सुधार, मिटाने, सीमित करने और आपत्ति करने का अधिकार है। किसी भी अनुरोध के लिए, <strong>[भरना है — संपर्क ईमेल]</strong> से संपर्क करें। आप अपने डेटा सुरक्षा प्राधिकरण से भी संपर्क कर सकते हैं।</p></section>'
) ON CONFLICT (key) DO NOTHING;
