// Correspondance pays -> continent, pour les 240 pays/territoires déjà
// référencés dans country_capitals.js (même périmètre, vérifié
// automatiquement lors de la génération de ce fichier : les 240 codes sont
// couverts exactement une fois chacun, aucun manque ni doublon).
//
// Sert à faire remonter une notification à portée continentale (ex. EUR)
// jusqu'aux abonnés d'un pays membre (ex. FRA) — voir
// workers/pushNotifications.js. Classification standard (schéma pratique
// proche du géoschéma ONU) ; quelques cas transcontinentaux tranchés par
// convention courante plutôt que par débat géopolitique : Russie et Chypre
// en EUR, Turquie, Géorgie, Arménie et Azerbaïdjan en ASI, Mexique et
// Caraïbes en NAC (Amérique du Nord au sens large, incluant l'Amérique
// centrale — convention courante, distincte du Canada/États-Unis seuls).

export const COUNTRY_TO_CONTINENT = {
  AGO: "AFR",
  BDI: "AFR",
  BEN: "AFR",
  BFA: "AFR",
  BWA: "AFR",
  CAF: "AFR",
  CIV: "AFR",
  CMR: "AFR",
  COD: "AFR",
  COG: "AFR",
  COM: "AFR",
  CPV: "AFR",
  DJI: "AFR",
  DZA: "AFR",
  EGY: "AFR",
  ERI: "AFR",
  ETH: "AFR",
  GAB: "AFR",
  GHA: "AFR",
  GIN: "AFR",
  GMB: "AFR",
  GNB: "AFR",
  GNQ: "AFR",
  KEN: "AFR",
  LBR: "AFR",
  LBY: "AFR",
  LSO: "AFR",
  MAR: "AFR",
  MDG: "AFR",
  MLI: "AFR",
  MOZ: "AFR",
  MRT: "AFR",
  MUS: "AFR",
  MWI: "AFR",
  MYT: "AFR",
  NAM: "AFR",
  NER: "AFR",
  NGA: "AFR",
  REU: "AFR",
  RWA: "AFR",
  SDN: "AFR",
  SEN: "AFR",
  SHN: "AFR",
  SLE: "AFR",
  SOM: "AFR",
  SSD: "AFR",
  STP: "AFR",
  SWZ: "AFR",
  SYC: "AFR",
  TCD: "AFR",
  TGO: "AFR",
  TUN: "AFR",
  TZA: "AFR",
  UGA: "AFR",
  ZAF: "AFR",
  ZMB: "AFR",
  ZWE: "AFR",
  ABW: "NAC",
  AIA: "NAC",
  ATG: "NAC",
  BES: "NAC",
  BHS: "NAC",
  BLM: "NAC",
  BLZ: "NAC",
  BMU: "NAC",
  BRB: "NAC",
  CAN: "NAC",
  CRI: "NAC",
  CUB: "NAC",
  CUW: "NAC",
  CYM: "NAC",
  DMA: "NAC",
  DOM: "NAC",
  GLP: "NAC",
  GRD: "NAC",
  GRL: "NAC",
  GTM: "NAC",
  HND: "NAC",
  HTI: "NAC",
  JAM: "NAC",
  KNA: "NAC",
  LCA: "NAC",
  MAF: "NAC",
  MEX: "NAC",
  MSR: "NAC",
  MTQ: "NAC",
  NIC: "NAC",
  PAN: "NAC",
  PRI: "NAC",
  SLV: "NAC",
  SPM: "NAC",
  SXM: "NAC",
  TCA: "NAC",
  TTO: "NAC",
  USA: "NAC",
  VCT: "NAC",
  VGB: "NAC",
  VIR: "NAC",
  ARG: "SAM",
  BOL: "SAM",
  BRA: "SAM",
  CHL: "SAM",
  COL: "SAM",
  ECU: "SAM",
  FLK: "SAM",
  GUF: "SAM",
  GUY: "SAM",
  PER: "SAM",
  PRY: "SAM",
  SUR: "SAM",
  URY: "SAM",
  VEN: "SAM",
  AFG: "ASI",
  ARE: "ASI",
  ARM: "ASI",
  AZE: "ASI",
  BGD: "ASI",
  BHR: "ASI",
  BRN: "ASI",
  BTN: "ASI",
  CCK: "ASI",
  CHN: "ASI",
  GEO: "ASI",
  HKG: "ASI",
  IDN: "ASI",
  IND: "ASI",
  IRN: "ASI",
  IRQ: "ASI",
  ISR: "ASI",
  JOR: "ASI",
  JPN: "ASI",
  KAZ: "ASI",
  KGZ: "ASI",
  KHM: "ASI",
  KOR: "ASI",
  KWT: "ASI",
  LAO: "ASI",
  LBN: "ASI",
  LKA: "ASI",
  MAC: "ASI",
  MDV: "ASI",
  MMR: "ASI",
  MNG: "ASI",
  MYS: "ASI",
  NPL: "ASI",
  OMN: "ASI",
  PAK: "ASI",
  PHL: "ASI",
  PRK: "ASI",
  PSE: "ASI",
  QAT: "ASI",
  SAU: "ASI",
  SGP: "ASI",
  SYR: "ASI",
  THA: "ASI",
  TJK: "ASI",
  TKM: "ASI",
  TLS: "ASI",
  TUR: "ASI",
  TWN: "ASI",
  UZB: "ASI",
  VNM: "ASI",
  YEM: "ASI",
  ALA: "EUR",
  ALB: "EUR",
  AND: "EUR",
  AUT: "EUR",
  BEL: "EUR",
  BGR: "EUR",
  BIH: "EUR",
  BLR: "EUR",
  CHE: "EUR",
  CYP: "EUR",
  CZE: "EUR",
  DEU: "EUR",
  DNK: "EUR",
  ESP: "EUR",
  EST: "EUR",
  FIN: "EUR",
  FRA: "EUR",
  FRO: "EUR",
  GBR: "EUR",
  GIB: "EUR",
  GRC: "EUR",
  HRV: "EUR",
  HUN: "EUR",
  IMN: "EUR",
  IRL: "EUR",
  ISL: "EUR",
  ITA: "EUR",
  JEY: "EUR",
  LIE: "EUR",
  LTU: "EUR",
  LUX: "EUR",
  LVA: "EUR",
  MCO: "EUR",
  MDA: "EUR",
  MKD: "EUR",
  MLT: "EUR",
  MNE: "EUR",
  NLD: "EUR",
  NOR: "EUR",
  POL: "EUR",
  PRT: "EUR",
  ROU: "EUR",
  RUS: "EUR",
  SJM: "EUR",
  SMR: "EUR",
  SRB: "EUR",
  SVK: "EUR",
  SVN: "EUR",
  SWE: "EUR",
  UKR: "EUR",
  VAT: "EUR",
  ASM: "OCE",
  AUS: "OCE",
  COK: "OCE",
  CXR: "OCE",
  FJI: "OCE",
  FSM: "OCE",
  GUM: "OCE",
  KIR: "OCE",
  MHL: "OCE",
  MNP: "OCE",
  NCL: "OCE",
  NFK: "OCE",
  NIU: "OCE",
  NRU: "OCE",
  NZL: "OCE",
  PCN: "OCE",
  PLW: "OCE",
  PNG: "OCE",
  PYF: "OCE",
  SLB: "OCE",
  TON: "OCE",
  TUV: "OCE",
  VUT: "OCE",
  WLF: "OCE",
  WSM: "OCE",
  ATF: "ANT",
};

// L'inverse : pour un continent donné, la liste de ses pays membres.
export const CONTINENT_TO_COUNTRIES = {
  AFR: ["AGO", "BDI", "BEN", "BFA", "BWA", "CAF", "CIV", "CMR", "COD", "COG", "COM", "CPV", "DJI", "DZA", "EGY", "ERI", "ETH", "GAB", "GHA", "GIN", "GMB", "GNB", "GNQ", "KEN", "LBR", "LBY", "LSO", "MAR", "MDG", "MLI", "MOZ", "MRT", "MUS", "MWI", "MYT", "NAM", "NER", "NGA", "REU", "RWA", "SDN", "SEN", "SHN", "SLE", "SOM", "SSD", "STP", "SWZ", "SYC", "TCD", "TGO", "TUN", "TZA", "UGA", "ZAF", "ZMB", "ZWE"],
  NAC: ["ABW", "AIA", "ATG", "BES", "BHS", "BLM", "BLZ", "BMU", "BRB", "CAN", "CRI", "CUB", "CUW", "CYM", "DMA", "DOM", "GLP", "GRD", "GRL", "GTM", "HND", "HTI", "JAM", "KNA", "LCA", "MAF", "MEX", "MSR", "MTQ", "NIC", "PAN", "PRI", "SLV", "SPM", "SXM", "TCA", "TTO", "USA", "VCT", "VGB", "VIR"],
  SAM: ["ARG", "BOL", "BRA", "CHL", "COL", "ECU", "FLK", "GUF", "GUY", "PER", "PRY", "SUR", "URY", "VEN"],
  ASI: ["AFG", "ARE", "ARM", "AZE", "BGD", "BHR", "BRN", "BTN", "CCK", "CHN", "GEO", "HKG", "IDN", "IND", "IRN", "IRQ", "ISR", "JOR", "JPN", "KAZ", "KGZ", "KHM", "KOR", "KWT", "LAO", "LBN", "LKA", "MAC", "MDV", "MMR", "MNG", "MYS", "NPL", "OMN", "PAK", "PHL", "PRK", "PSE", "QAT", "SAU", "SGP", "SYR", "THA", "TJK", "TKM", "TLS", "TUR", "TWN", "UZB", "VNM", "YEM"],
  EUR: ["ALA", "ALB", "AND", "AUT", "BEL", "BGR", "BIH", "BLR", "CHE", "CYP", "CZE", "DEU", "DNK", "ESP", "EST", "FIN", "FRA", "FRO", "GBR", "GIB", "GRC", "HRV", "HUN", "IMN", "IRL", "ISL", "ITA", "JEY", "LIE", "LTU", "LUX", "LVA", "MCO", "MDA", "MKD", "MLT", "MNE", "NLD", "NOR", "POL", "PRT", "ROU", "RUS", "SJM", "SMR", "SRB", "SVK", "SVN", "SWE", "UKR", "VAT"],
  OCE: ["ASM", "AUS", "COK", "CXR", "FJI", "FSM", "GUM", "KIR", "MHL", "MNP", "NCL", "NFK", "NIU", "NRU", "NZL", "PCN", "PLW", "PNG", "PYF", "SLB", "TON", "TUV", "VUT", "WLF", "WSM"],
  ANT: ["ATF"],
};

