export const labelsFr = {
  lang: "fr",
  world: "Monde",
  page1Eyebrow: "CLIMAT OBSERVÉ",
  page1TitleLine1: "Le climat a déjà changé.",
  page1TitleLine2: "Mesuré, pas estimé.",
  page1Subtitle: "Chaque bande ci-dessus représente environ 5 ans, du bleu (plus froid que la référence) au rouge foncé (plus chaud) — aucune projection, uniquement des données observées.",
  referenceLabel: "écart à la référence 1991-2020",
  samePeriod: "même période",
  franceTempNote: "Réchauffement mesuré sur la période de référence utilisée par l'OMM.",
  heatwaveTag: "VAGUES DE CHALEUR • DONNÉES OBSERVÉES",
  heatwaveHeadline: (ratio) => (ratio ? `${ratio} fois plus nombreuses ces 35 dernières années.` : "Évolution des vagues de chaleur."),
  heatwaveDetail: "Entre 1991 et 2025 contre 1956-1990 — un comptage réel, année après année, pas une estimation.",
  wavesLabel: "vagues",
  energyTitle: (country) => `ÉLECTRICITÉ • LES 3 PRINCIPALES SOURCES DE ${country.toUpperCase()}`,
  energyUnavailable: "Données de mix énergétique non disponibles pour ce pays.",
  retenirLabel: "À retenir",
  retenirText: "Ces chiffres viennent de relevés météorologiques historiques (Open-Meteo / ERA5), jamais de scénarios pour le futur.",
  sourcesTemperature: "Sources : Open-Meteo (ERA5) • pasdeplaneteb.com",

  page2Eyebrow: "RESSOURCES & VIVANT",
  page2TitleLine1: "Ce que nous prélevons.",
  page2TitleLine2: "Ce que le vivant nous dit.",
  page2Subtitle: "Six indicateurs, toujours avec leur repère mondial — jamais un chiffre isolé.",
  eauSubnote: "Prélevée à la source, pas nécessairement consommée — une partie retourne au milieu naturel après usage.",
  legendFrance: (country) => `position de ${country}`,
  legendWorld: "moyenne mondiale (simple repère, pas un objectif)",
  narrativeCaveat: "Certains écarts s'expliquent par la taille ou la richesse naturelle du pays, pas uniquement par ses choix — à lire dans cet esprit.",
  closingTitle: "Comprendre. Comparer. Agir.",
  closingText: "Retrouvez les données, les sources et les comparaisons pays par pays.",
  sourcesGeneral: "Sources : Global Carbon Budget/OWID • RTE • SDES/OFB • Open-Meteo • pasdeplaneteb.com",

  indicators: {
    co2: "CO2 / hab. / an",
    electricite: "Électricité / hab. / an",
    eau: "Eau prélevée / hab. / an",
    foret: "Forêt perdue / an",
    pollution: "Pollution PM2.5",
    especes: "Espèces menacées",
  },
};
