export const labelsEs = {
  lang: "es",
  world: "Mundo",
  page1Eyebrow: "CLIMA OBSERVADO",
  page1TitleLine1: "El clima ya ha cambiado.",
  page1TitleLine2: "Medido, no estimado.",
  page1Subtitle: "Cada franja representa unos 5 años, del azul (más frío que la referencia) al rojo oscuro (más cálido) — sin proyecciones, solo datos observados.",
  referenceLabel: "desviación respecto a la referencia 1991-2020",
  samePeriod: "mismo período",
  franceTempNote: "Calentamiento medido sobre el período de referencia utilizado por la OMM.",
  heatwaveTag: "OLAS DE CALOR • DATOS OBSERVADOS",
  heatwaveHeadline: (ratio) => (ratio ? `${ratio} veces más frecuentes en los últimos 35 años.` : "Evolución de las olas de calor."),
  heatwaveDetail: "Entre 1991-2025 frente a 1956-1990 — un recuento real, año tras año, no una estimación.",
  wavesLabel: "olas",
  energyTitle: (country) => `ELECTRICIDAD • LAS 3 PRINCIPALES FUENTES DE ${country.toUpperCase()}`,
  energyUnavailable: "Datos de la combinación energética no disponibles para este país.",
  retenirLabel: "Para recordar",
  retenirText: "Estas cifras proceden de registros meteorológicos históricos (Open-Meteo / ERA5), nunca de escenarios futuros.",
  sourcesTemperature: "Fuentes: Open-Meteo (ERA5) • pasdeplaneteb.com",

  page2Eyebrow: "RECURSOS Y VIDA SILVESTRE",
  page2TitleLine1: "Lo que extraemos.",
  page2TitleLine2: "Lo que nos dice la vida silvestre.",
  page2Subtitle: "Seis indicadores, siempre con su referencia mundial — nunca una cifra aislada.",
  eauSubnote: "Extraída de la fuente, no necesariamente consumida — parte de ella vuelve al medio natural tras su uso.",
  legendFrance: (country) => `${country}`,
  legendWorld: "media mundial (una referencia, no un objetivo)",
  narrativeCaveat: "Algunas diferencias se explican por el tamaño o la riqueza natural del país, no solo por sus decisiones — léase con ese matiz.",
  closingTitle: "Comprender. Comparar. Actuar.",
  closingText: "Encuentre los datos, las fuentes y las comparaciones entre países.",
  sourcesGeneral: "Fuentes: Global Carbon Budget/OWID • RTE • SDES/OFB • Open-Meteo • pasdeplaneteb.com",

  indicators: {
    co2: "CO2 / hab. / año",
    electricite: "Electricidad / hab. / año",
    eau: "Agua extraída / hab. / año",
    foret: "Bosque perdido / año",
    pollution: "Contaminación PM2.5",
    especes: "Especies amenazadas",
  },

  worldTempNote: (ratio, faster, country) => faster
    ? `${country} se está calentando ${ratio} veces más rápido que la media mundial.`
    : `${country} se está calentando ${ratio} veces más despacio que la media mundial.`,
  heatwaveNarrative: "Una ola de calor no es un simple pico puntual: es un período de al menos 5 días consecutivos en los que las temperaturas superan claramente las normas estacionales. Su aumento en una sola generación no es una previsión — es lo que las estaciones meteorológicas han registrado realmente, año tras año, en todo el territorio.",
  energyRest: (pct) => `El ${pct}% restante se reparte entre otras fuentes de energía.`,

  ogFallbackTitle: "Datos abiertos sobre clima y medio ambiente",
  ogTagline: "Kit de comunicación — datos abiertos y verificados",

  energySources: {
    nuclear: "Nuclear",
    hydro: "Hidráulica",
    gas: "Gas",
    coal: "Carbón",
    wind: "Eólica",
    solar: "Solar",
    oil: "Petróleo",
    biofuel: "Bioenergía",
    other: "Otras renovables",
  },
};
