export const labelsEn = {
  lang: "en",
  world: "World",
  page1Eyebrow: "OBSERVED CLIMATE",
  page1TitleLine1: "The climate has already changed.",
  page1TitleLine2: "Measured, not estimated.",
  page1Subtitle: "Each band above represents about 5 years, from blue (colder than the reference) to dark red (warmer) — no projections, only observed data.",
  referenceLabel: "deviation from the 1991-2020 reference",
  samePeriod: "same period",
  franceTempNote: "Warming measured over the reference period used by the WMO.",
  heatwaveTag: "HEATWAVES • OBSERVED DATA",
  heatwaveHeadline: (ratio) => (ratio ? `${ratio} times more frequent over the last 35 years.` : "Heatwave trend."),
  heatwaveDetail: "Between 1991-2025 versus 1956-1990 — an actual year-by-year count, not an estimate.",
  wavesLabel: "heatwaves",
  energyTitle: (country) => `ELECTRICITY • TOP 3 SOURCES IN ${country.toUpperCase()}`,
  energyUnavailable: "Energy mix data not available for this country.",
  retenirLabel: "Key takeaway",
  retenirText: "These figures come from historical weather records (Open-Meteo / ERA5), never from future scenarios.",
  sourcesTemperature: "Sources: Open-Meteo (ERA5) • pasdeplaneteb.com",

  page2Eyebrow: "RESOURCES & WILDLIFE",
  page2TitleLine1: "What we take.",
  page2TitleLine2: "What wildlife tells us.",
  page2Subtitle: "Six indicators, always with their global benchmark — never a figure in isolation.",
  eauSubnote: "Withdrawn from the source, not necessarily consumed — some of it returns to the environment after use.",
  legendFrance: (country) => `${country}`,
  legendWorld: "world average (a reference point, not a target)",
  narrativeCaveat: "Some gaps are explained by a country's size or natural wealth, not solely by its choices — read with that in mind.",
  closingTitle: "Understand. Compare. Act.",
  closingText: "Find the data, sources, and country comparisons.",
  sourcesGeneral: "Sources: Global Carbon Budget/OWID • RTE • SDES/OFB • Open-Meteo • pasdeplaneteb.com",

  indicators: {
    co2: "CO2 / capita / year",
    electricite: "Electricity / capita / year",
    eau: "Water withdrawn / capita / year",
    foret: "Forest lost / year",
    pollution: "PM2.5 pollution",
    especes: "Threatened species",
  },

  worldTempNote: (ratio, faster, country) => faster
    ? `${country} is warming ${ratio} times faster than the world average.`
    : `${country} is warming ${ratio} times slower than the world average.`,
  heatwaveNarrative: "A heatwave is not a single, brief spike: it's a period of at least 5 consecutive days where temperatures are markedly above seasonal norms. Their increase within a single generation is not a forecast — it's what weather stations have actually recorded, year after year, across the whole territory.",
  energyRest: (pct) => `The remaining ${pct}% is spread across other energy sources.`,

  energySources: {
    nuclear: "Nuclear",
    hydro: "Hydro",
    gas: "Gas",
    coal: "Coal",
    wind: "Wind",
    solar: "Solar",
    oil: "Oil",
    biofuel: "Bioenergy",
    other: "Other renewables",
  },
};
