export const labelsHi = {
  lang: "hi",
  world: "विश्व",
  page1Eyebrow: "अवलोकित जलवायु",
  page1TitleLine1: "जलवायु पहले ही बदल चुकी है।",
  page1TitleLine2: "मापा गया, अनुमानित नहीं।",
  page1Subtitle: "ऊपर हर पट्टी लगभग 5 वर्षों को दर्शाती है, नीले (संदर्भ से ठंडा) से गहरे लाल (अधिक गर्म) तक — कोई अनुमान नहीं, केवल वास्तविक अवलोकित डेटा।",
  referenceLabel: "1991-2020 संदर्भ से विचलन",
  samePeriod: "वही अवधि",
  franceTempNote: "WMO द्वारा उपयोग की जाने वाली संदर्भ अवधि पर मापी गई गर्मी।",
  heatwaveTag: "लू • अवलोकित डेटा",
  heatwaveHeadline: (ratio) => (ratio ? `पिछले 35 वर्षों में ${ratio} गुना अधिक बार।` : "लू की प्रवृत्ति।"),
  heatwaveDetail: "1991-2025 की तुलना 1956-1990 से — अनुमान नहीं, वर्ष-दर-वर्ष वास्तविक गिनती।",
  wavesLabel: "बार",
  energyTitle: (country) => `बिजली • ${country} के 3 मुख्य स्रोत`,
  energyUnavailable: "इस देश के लिए ऊर्जा मिश्रण डेटा उपलब्ध नहीं है।",
  retenirLabel: "याद रखें",
  retenirText: "ये आंकड़े ऐतिहासिक मौसम रिकॉर्ड (Open-Meteo / ERA5) से हैं, भविष्य के परिदृश्यों से कभी नहीं।",
  sourcesTemperature: "स्रोत: Open-Meteo (ERA5) • pasdeplaneteb.com",

  page2Eyebrow: "संसाधन और वन्यजीवन",
  page2TitleLine1: "हम जो लेते हैं।",
  page2TitleLine2: "वन्यजीवन जो हमें बताता है।",
  page2Subtitle: "छह संकेतक, हमेशा अपने वैश्विक मानदंड के साथ — कभी भी अकेला आंकड़ा नहीं।",
  eauSubnote: "स्रोत से निकाला गया, जरूरी नहीं कि उपभोग किया गया हो — उपयोग के बाद इसका कुछ हिस्सा प्राकृतिक पर्यावरण में लौट आता है।",
  legendFrance: (country) => `${country}`,
  legendWorld: "वैश्विक औसत (केवल एक संदर्भ बिंदु, लक्ष्य नहीं)",
  narrativeCaveat: "कुछ अंतर देश के आकार या प्राकृतिक संपदा से समझाए जाते हैं, केवल उसकी पसंद से नहीं — इसी भावना से पढ़ें।",
  closingTitle: "समझें। तुलना करें। कार्य करें।",
  closingText: "डेटा, स्रोत और देशों की तुलना यहां पाएं।",
  sourcesGeneral: "स्रोत: Global Carbon Budget/OWID • RTE • SDES/OFB • Open-Meteo • pasdeplaneteb.com",

  indicators: {
    co2: "CO2 / व्यक्ति / वर्ष",
    electricite: "बिजली / व्यक्ति / वर्ष",
    eau: "निकाला गया पानी / व्यक्ति / वर्ष",
    foret: "वन हानि / वर्ष",
    pollution: "PM2.5 प्रदूषण",
    especes: "संकटग्रस्त प्रजातियां",
  },

  energySources: {
    nuclear: "परमाणु",
    hydro: "जलविद्युत",
    gas: "गैस",
    coal: "कोयला",
    wind: "पवन",
    solar: "सौर",
    oil: "तेल",
    biofuel: "जैव ऊर्जा",
    other: "अन्य नवीकरणीय",
  },
};
