export const labelsFr = {
  lang: "fr",
  world: "Monde",
  page1Eyebrow: "CLIMAT OBSERVÉ",
  page1TitleLine1: "Le climat a déjà changé.",
  page1TitleLine2: "Mesuré, pas estimé.",
  page1Subtitle: "Chaque bande ci-dessus représente environ 5 ans, du bleu (plus froid que la référence) au rouge foncé (plus chaud) — aucune projection, uniquement des données observées.",
  referenceLabel: "écart à la référence 1991-2020",
  samePeriod: "même période",
  franceTempNote: "Réchauffement mesuré sur la période de référence utilisée par l'OMM.",
  heatwaveTag: "VAGUES DE CHALEUR • DONNÉES OBSERVÉES",
  heatwaveHeadline: (ratio) => (ratio ? `${ratio} fois plus nombreuses ces 35 dernières années.` : "Évolution des vagues de chaleur."),
  heatwaveDetail: "Entre 1991 et 2025 contre 1956-1990 — un comptage réel, année après année, pas une estimation.",
  wavesLabel: "vagues",
  energyTitle: (country) => `ÉLECTRICITÉ • LES 3 PRINCIPALES SOURCES DE ${country.toUpperCase()}`,
  energyUnavailable: "Données de mix énergétique non disponibles pour ce pays.",
  retenirLabel: "À retenir",
  retenirText: "Ces chiffres viennent de relevés météorologiques historiques (Open-Meteo / ERA5), jamais de scénarios pour le futur.",
  sourcesTemperature: "Sources : Open-Meteo (ERA5) • pasdeplaneteb.com",

  page2Eyebrow: "RESSOURCES & VIVANT",
  page2TitleLine1: "Ce que nous prélevons.",
  page2TitleLine2: "Ce que le vivant nous dit.",
  page2Subtitle: "Six indicateurs, toujours avec leur repère mondial — jamais un chiffre isolé.",
  eauSubnote: "Prélevée à la source, pas nécessairement consommée — une partie retourne au milieu naturel après usage.",
  legendFrance: (country) => `${country}`,
  legendWorld: "moyenne mondiale (simple repère, pas un objectif)",
  narrativeCaveat: "Certains écarts s'expliquent par la taille ou la richesse naturelle du pays, pas uniquement par ses choix — à lire dans cet esprit.",
  closingTitle: "Comprendre. Comparer. Agir.",
  closingText: "Retrouvez les données, les sources et les comparaisons pays par pays.",
  sourcesGeneral: "Sources : Global Carbon Budget/OWID • RTE • SDES/OFB • Open-Meteo • pasdeplaneteb.com",

  indicators: {
    co2: "CO2 / hab. / an",
    electricite: "Électricité / hab. / an",
    eau: "Eau prélevée / hab. / an",
    foret: "Forêt perdue / an",
    pollution: "Pollution PM2.5",
    especes: "Espèces menacées",
  },

  worldTempNote: (ratio, faster, country) => faster
    ? `${country} se réchauffe ${ratio} fois plus vite que la moyenne mondiale.`
    : `${country} se réchauffe ${ratio} fois moins vite que la moyenne mondiale.`,
  heatwaveNarrative: "Une vague de chaleur n'est pas un simple pic ponctuel : c'est une période d'au moins 5 jours consécutifs où les températures dépassent nettement les normales de saison. Leur multiplication en une génération n'est pas une prévision — c'est ce que les stations météorologiques ont effectivement enregistré, année après année, sur l'ensemble du territoire.",
  energyRest: (pct) => `Le reste (${pct} %) réparti entre les autres sources d'énergie.`,

  energySources: {
    nuclear: "Nucléaire",
    hydro: "Hydraulique",
    gas: "Gaz",
    coal: "Charbon",
    wind: "Éolien",
    solar: "Solaire",
    oil: "Pétrole",
    biofuel: "Bioénergie",
    other: "Autres renouvelables",
  },
};
