export const labelsIt = {
  lang: "it",
  world: "Mondo",
  page1Eyebrow: "CLIMA OSSERVATO",
  page1TitleLine1: "Il clima è già cambiato.",
  page1TitleLine2: "Misurato, non stimato.",
  page1Subtitle: "Ogni fascia rappresenta circa 5 anni, dal blu (più freddo della media di riferimento) al rosso scuro (più caldo) — nessuna proiezione, solo dati osservati.",
  referenceLabel: "scostamento dal riferimento 1991-2020",
  samePeriod: "stesso periodo",
  franceTempNote: "Riscaldamento misurato sul periodo di riferimento utilizzato dall'OMM.",
  heatwaveTag: "ONDATE DI CALORE • DATI OSSERVATI",
  heatwaveHeadline: (ratio) => (ratio ? `${ratio} volte più frequenti negli ultimi 35 anni.` : "Andamento delle ondate di calore."),
  heatwaveDetail: "Tra il 1991-2025 e il 1956-1990 — un conteggio reale, anno per anno, non una stima.",
  wavesLabel: "ondate",
  energyTitle: (country) => `ELETTRICITÀ • LE 3 PRINCIPALI FONTI DI ${country.toUpperCase()}`,
  energyUnavailable: "Dati sul mix energetico non disponibili per questo paese.",
  retenirLabel: "Da ricordare",
  retenirText: "Questi dati provengono da rilevazioni meteorologiche storiche (Open-Meteo / ERA5), mai da scenari futuri.",
  sourcesTemperature: "Fonti: Open-Meteo (ERA5) • pasdeplaneteb.com",

  page2Eyebrow: "RISORSE E BIODIVERSITÀ",
  page2TitleLine1: "Ciò che prendiamo.",
  page2TitleLine2: "Ciò che la natura ci dice.",
  page2Subtitle: "Sei indicatori, sempre con il loro riferimento mondiale — mai un dato isolato.",
  eauSubnote: "Prelevata alla fonte, non necessariamente consumata — una parte ritorna nell'ambiente naturale dopo l'uso.",
  legendFrance: (country) => `${country}`,
  legendWorld: "media mondiale (un semplice riferimento, non un obiettivo)",
  narrativeCaveat: "Alcune differenze si spiegano con le dimensioni o la ricchezza naturale del paese, non solo con le sue scelte — da leggere in questo spirito.",
  closingTitle: "Capire. Confrontare. Agire.",
  closingText: "Trova i dati, le fonti e i confronti tra paesi.",
  sourcesGeneral: "Fonti: Global Carbon Budget/OWID • RTE • SDES/OFB • Open-Meteo • pasdeplaneteb.com",

  indicators: {
    co2: "CO2 / ab. / anno",
    electricite: "Elettricità / ab. / anno",
    eau: "Acqua prelevata / ab. / anno",
    foret: "Foresta persa / anno",
    pollution: "Inquinamento PM2.5",
    especes: "Specie minacciate",
  },

  worldTempNote: (ratio, faster, country) => faster
    ? `${country} si sta riscaldando ${ratio} volte più velocemente della media mondiale.`
    : `${country} si sta riscaldando ${ratio} volte più lentamente della media mondiale.`,
  heatwaveNarrative: "Un'ondata di calore non è un semplice picco isolato: è un periodo di almeno 5 giorni consecutivi in cui le temperature superano nettamente le medie stagionali. Il loro aumento nel giro di una generazione non è una previsione — è ciò che le stazioni meteorologiche hanno effettivamente registrato, anno dopo anno, su tutto il territorio.",
  energyRest: (pct) => `Il restante ${pct}% è distribuito tra le altre fonti energetiche.`,

  ogFallbackTitle: "Dati aperti su clima e ambiente",
  ogTagline: "Kit di comunicazione — dati aperti e verificati",

  energySources: {
    nuclear: "Nucleare",
    hydro: "Idroelettrica",
    gas: "Gas",
    coal: "Carbone",
    wind: "Eolica",
    solar: "Solare",
    oil: "Petrolio",
    biofuel: "Bioenergia",
    other: "Altre rinnovabili",
  },
};
