export const labelsZh = {
  lang: "zh",
  world: "全球",
  page1Eyebrow: "观测气候",
  page1TitleLine1: "气候已经发生变化。",
  page1TitleLine2: "实测数据，而非估算。",
  page1Subtitle: "上方每条色带代表约5年，从蓝色（比基准更冷）到深红色（更热）——不含任何预测，仅为观测数据。",
  referenceLabel: "与1991-2020基准的偏差",
  samePeriod: "同一时期",
  franceTempNote: "根据世界气象组织采用的基准期测得的升温幅度。",
  heatwaveTag: "热浪 • 观测数据",
  heatwaveHeadline: (ratio) => (ratio ? `过去35年增加了${ratio}倍。` : "热浪变化趋势。"),
  heatwaveDetail: "1991-2025年与1956-1990年相比——逐年实际统计，而非估算。",
  wavesLabel: "次",
  energyTitle: (country) => `电力 • ${country}的三大主要能源`,
  energyUnavailable: "该国的能源结构数据不可用。",
  retenirLabel: "要点",
  retenirText: "这些数据来自历史气象记录（Open-Meteo / ERA5），绝非未来情景预测。",
  sourcesTemperature: "来源：Open-Meteo（ERA5）• pasdeplaneteb.com",

  page2Eyebrow: "资源与生物多样性",
  page2TitleLine1: "我们索取的。",
  page2TitleLine2: "自然告诉我们的。",
  page2Subtitle: "六项指标，始终附有全球参照值——从不孤立呈现。",
  eauSubnote: "取自水源，未必被消耗——部分在使用后会回归自然环境。",
  legendFrance: (country) => `${country}`,
  legendWorld: "全球平均值（仅作参考，非目标）",
  narrativeCaveat: "部分差异源于该国的国土面积或自然禀赋，而不仅仅是其自身选择——请以此视角解读。",
  closingTitle: "理解。比较。行动。",
  closingText: "查看数据、来源及各国对比。",
  sourcesGeneral: "来源：Global Carbon Budget/OWID • RTE • SDES/OFB • Open-Meteo • pasdeplaneteb.com",

  indicators: {
    co2: "人均CO2 / 年",
    electricite: "人均用电量 / 年",
    eau: "人均取水量 / 年",
    foret: "森林流失 / 年",
    pollution: "PM2.5污染",
    especes: "受威胁物种",
  },

  worldTempNote: (ratio, faster, country) => faster
    ? `${country}的升温速度是全球平均水平的${ratio}倍。`
    : `${country}的升温速度比全球平均水平慢${ratio}倍。`,
  heatwaveNarrative: "热浪并非短暂的单一高峰：它是指气温明显高于季节常态、持续至少5天的时期。其在一代人时间内的增加并非预测——而是气象站在全国范围内逐年实际记录的结果。",
  energyRest: (pct) => `其余${pct}%分布在其他能源之间。`,

  energySources: {
    nuclear: "核能",
    hydro: "水力",
    gas: "天然气",
    coal: "煤炭",
    wind: "风能",
    solar: "太阳能",
    oil: "石油",
    biofuel: "生物能源",
    other: "其他可再生能源",
  },
};
