export const labelsJa = {
  lang: "ja",
  world: "世界",
  page1Eyebrow: "観測された気候",
  page1TitleLine1: "気候はすでに変化しています。",
  page1TitleLine2: "推定ではなく、実測値です。",
  page1Subtitle: "上のバンドはそれぞれ約5年間を表し、青（基準より寒い）から濃い赤（暑い）まで — 予測ではなく、実測データのみを使用しています。",
  referenceLabel: "1991-2020年基準からの偏差",
  samePeriod: "同期間",
  franceTempNote: "WMO（世界気象機関）が使用する基準期間で測定された温暖化。",
  heatwaveTag: "熱波 • 観測データ",
  heatwaveHeadline: (ratio) => (ratio ? `過去35年間で${ratio}倍に増加。` : "熱波の推移。"),
  heatwaveDetail: "1991-2025年と1956-1990年の比較 — 推定ではなく、年ごとの実際の集計です。",
  wavesLabel: "回",
  energyTitle: (country) => `電力 • ${country}の主要3電源`,
  energyUnavailable: "この国のエネルギー構成データは利用できません。",
  retenirLabel: "まとめ",
  retenirText: "これらの数値は過去の気象記録（Open-Meteo / ERA5）によるもので、将来のシナリオではありません。",
  sourcesTemperature: "出典：Open-Meteo（ERA5）• pasdeplaneteb.com",

  page2Eyebrow: "資源と生態系",
  page2TitleLine1: "私たちが使っているもの。",
  page2TitleLine2: "生態系が伝えていること。",
  page2Subtitle: "6つの指標は、常に世界の基準値とともに示します — 単独の数字は使いません。",
  eauSubnote: "水源から取水されたものであり、必ずしも消費されるわけではありません — 使用後に自然環境へ戻る分もあります。",
  legendFrance: (country) => `${country}`,
  legendWorld: "世界平均（目標ではなく単なる目安）",
  narrativeCaveat: "差の一部は国の規模や自然の豊かさによるもので、必ずしもその国の選択だけによるものではありません — その点を踏まえてお読みください。",
  closingTitle: "理解する。比較する。行動する。",
  closingText: "データ、出典、国別比較はこちらでご覧いただけます。",
  sourcesGeneral: "出典：Global Carbon Budget/OWID • RTE • SDES/OFB • Open-Meteo • pasdeplaneteb.com",

  indicators: {
    co2: "CO2 / 人 / 年",
    electricite: "電力 / 人 / 年",
    eau: "取水量 / 人 / 年",
    foret: "森林減少 / 年",
    pollution: "PM2.5汚染",
    especes: "絶滅危惧種",
  },

  worldTempNote: (ratio, faster, country) => faster
    ? `${country}は世界平均の${ratio}倍の速さで温暖化しています。`
    : `${country}の温暖化は世界平均よりゆるやかで、その差は${ratio}倍です。`,
  heatwaveNarrative: "熱波とは一時的な単発のピークではなく、季節の平年値を大きく上回る状態が5日以上続く期間を指します。一世代の間にその頻度が増加したことは予測ではなく、気象観測所が実際に、毎年、国内全域で記録してきた事実です。",
  energyRest: (pct) => `残りの${pct}％はその他のエネルギー源によるものです。`,

  ogFallbackTitle: "気候と環境に関するオープンデータ",
  ogTagline: "コミュニケーションキット — 出典明記のオープンデータ",

  energySources: {
    nuclear: "原子力",
    hydro: "水力",
    gas: "天然ガス",
    coal: "石炭",
    wind: "風力",
    solar: "太陽光",
    oil: "石油",
    biofuel: "バイオエネルギー",
    other: "その他再生可能エネルギー",
  },
};
